/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'youri' at '5/6/15 9:24 AM' with Gradle 2.4
 *
 * @author youri, @date 5/6/15 9:24 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
